version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIABLE: "variable"
    ports:
      - "8000:8000"
    restart: always
    environment:
      ENVIRONMENT: environment
    volumes:
      - .:/app
#     command: bash -c "spark.version"
#    command: bash -c "python -m solution"
    command: bash -c "tail -F anything"
    networks:
      - shared-network
    depends_on:
      - db

  db:
    image: postgres:14.4
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./.data:/var/lib/postgresql/data
    networks:
      - shared-network

networks:
  shared-network:
